import type { PublicationBase } from '@festivalarc/editions'

export type PublicationMetadataInput = { readonly siteOrigin: string; readonly base: PublicationBase; readonly pathname?: string; readonly title: string; readonly description?: string; readonly image?: string }
export type PublicationMetadata = { readonly canonical: string; readonly openGraph: Readonly<{ url: string; title: string; description?: string; image?: string }>; readonly twitter: Readonly<{ card: 'summary_large_image'; url: string; title: string; description?: string; image?: string }>; readonly jsonLd: Readonly<Record<string, unknown>>; readonly sitemap: string; readonly sitemapLink: string }
function origin(siteOrigin: string): URL { const value = new URL(siteOrigin); if (value.protocol !== 'https:' || value.pathname !== '/' || value.search || value.hash) throw new Error('siteOrigin must be an HTTPS origin'); return value }
function pathPart(pathname: string): string { if (!pathname || pathname === '/') return ''; if (/^[a-z][a-z\d+.-]*:/i.test(pathname) || pathname.includes('\\') || pathname.includes('\0')) throw new Error(`Invalid publication path: ${pathname}`); const parts = pathname.split('/').filter(Boolean); if (parts.some(part => part === '.' || part === '..')) throw new Error(`Invalid publication path: ${pathname}`); return `/${parts.join('/')}` }
export function publicPath(base: PublicationBase, pathname = '/'): string { const prefix = base === '/' ? '' : base.replace(/\/$/, ''); return `${prefix}${pathPart(pathname)}` || '/' }
export function publicationUrl(siteOrigin: string, base: PublicationBase, pathname = '/'): string { return new URL(publicPath(base, pathname), origin(siteOrigin)).toString().replace(/\/$/, '') }
function imageUrl(siteOrigin: string, base: PublicationBase, image: string): string { try { return new URL(image).toString() } catch { return publicationUrl(siteOrigin, base, image) } }
export function createPublicationMetadata(input: PublicationMetadataInput): PublicationMetadata { const canonical = publicationUrl(input.siteOrigin, input.base, input.pathname), sitemap = publicationUrl(input.siteOrigin, '' as PublicationBase, '/sitemap-index.xml'), image = input.image && imageUrl(input.siteOrigin, input.base, input.image), common = { title: input.title, ...(input.description ? { description: input.description } : {}), ...(image ? { image } : {}) }; return { canonical, openGraph: { url: canonical, ...common }, twitter: { card: 'summary_large_image', url: canonical, ...common }, jsonLd: { '@context': 'https://schema.org', '@type': 'WebPage', url: canonical, name: input.title, ...(input.description ? { description: input.description } : {}) }, sitemap, sitemapLink: sitemap } }
export const createMetadata = createPublicationMetadata
